company_map = {
    'realmex7pro' : 'realme',
    'iphone' : 'apple',
    'pocox3' : 'poco',
    'poco m2' : 'poco',
    'techno' : 'tecno',
    'one plus' : 'oneplus',
    'galaxy' : 'samsung',
    'xiamoi' : 'xiaomi',
    'moto' : 'motorola',
    'pixel' : 'google',
    'dimensity':'mediatek',
    'iqoo':'vivo',
    'पोको एफ 2' : 'poco',
    'आइफोन' : 'iphone',
    'गैलेक्सी' : 'galaxys',
    'अपलिफ्ट' : 'uplift',
    'आइफोन (एप्पल)' : 'apple',
    'रियलमी' : 'realme',
    'एक्सगोडी' : 'xgody',
    'शाओमी' : 'xiaomi',
    'हुवाई' : 'huawei',
    'मीडियाटेक' : 'mediatek',
    'आसूस' : 'asus',
    'एलजी' : 'lg',
    'जेडटीई' : 'zte',
    'टेक्नो' : 'tecno',
    'मोटोरोला' : 'motorola',
    'पोको एम 2' : 'poco',
    'वीवो' : 'vivo',
    'मोटो' : 'moto',
    'मी' : 'mi',
    'आईटेल' : 'itel',
    'एप्पल' : 'apple',
    'एसर' : 'acer',
    'पोको' : 'poco',
    'रेडमी' : 'redmi',
    'एचएमडी' : 'hmd',
    'सैमसंग' : 'samsung',
    'एचएमडी ग्लोबल (नोकिया)' : 'nokia',
    'माइक्रोमैक्स' : 'micromax',
    'आइस्‍मार्ट' : 'ismart',
    'गैलेक्सी (सैमसंग)' : 'samsung',
    'वन प्लस' : 'oneplus',
    'ब्लैक शार्क (शाओमी)' : 'xiaomi',
    'टेकोनो' : 'tecno',
    'लावा' : 'lava',
    'क्वालकॉम' : 'qualcomm',
    'कुओमस' : 'koomus',
    'एक्सिनोस' : 'exynos',
    'आई कॉल' : 'i kall',
    'सोनी' : 'sony',
    'बीएसएनएल' : 'bsnl',
    'जियो' : 'jio',
    'गूगल' : 'google',
    'कूलपैड' : 'coolpad',
    'ओप्पो' : 'oppo',
    'हॉनर' : 'honor',
    'वनप्लस' : 'oneplus',
    'नोकिया' : 'nokia',
    'पिक्सेल' : 'pixel',
    'पोट्रोनिक्स' : 'potronics',
    'मी' : 'mi',
    'एक्सोन' : 'axon',
    'लैनट्रोनिक्स': 'lantronics',
    'iphone(apple)' : 'apple',
    'iphone (apple)' : 'apple'
    # 'Bsnl' : 'BSNL',
    # 'Hmd' : 'HMD',
    # 'Zte' : 'ZTE',
    # 'Oneplus' : 'OnePlus',
    # 'Mediatek' : 'MediaTek',
    # 'Blackberry' : 'BlackBerry'

}